### ISSUE TITLE
Error When Starting

### ISSUE THREAD

**Issue by skyrawr** [Dracovian/Discord-Scraper#15]
`Traceback (most recent call last):
  File "discord.py", line 292, in <module>
    ds = DiscordScraper()
  File "discord.py", line 103, in __init__
    config = json_to_array(config_file.read())
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 23 column 2 (char 507)`

**Comment by Dracovian** [comment]
Hmm, sounds like an issue when grabbing text from a channel.

I figure this script is in need of an update, and this right here proves it.

**Comment by Dracovian** [comment]
Give the experimental branch script a test:
```
git clone https://github.com/Dracovian/Discord-Scraper
cd Discord-Scraper
git checkout experimental
```

Then let me know if this issue occurs.
The experimental branch is missing any text and DM content grabbing for the time-being, but it should be able to grab images, videos, and embedded content (depending on the source of the embedded content).
