### ISSUE TITLE
AttributeError: 'datetime.datetime' object has no attribute 'timestamp'

### ISSUE THREAD

**Issue by Ajinson** [Dracovian/Discord-Scraper#50]
when running the script i found this error. the directory of the "Discord Scrapes" are succesfully created but the content are empty. 

Traceback (most recent call last):
  File "discord.py", line 347, in <module>
    ds.grab_server_data()
  File "discord.py", line 327, in grab_server_data
    self.grab_data(folder, server, channel)
  File "discord.py", line 288, in grab_data
    today = get_day(date.day, date.month, date.year)
  File "discord.py", line 60, in get_day
    hour=0, minute=0, second=0).timestamp()
AttributeError: 'datetime.datetime' object has no attribute 'timestamp'

**Comment by Dracovian** [comment]
I just got through testing the following:
```py
from datetime import datetime
datetime(2020, 10, 1, 0, 0, 0).timestamp()
```

In the following versions of Python:

Python 3.8
Python 3.9

Without any error, but I then ran the same code in Python 2.7.18 and got the same error you posted.
I suppose if I am going to be pushing Python 2 support in this script alongside the Python 3 stuff in the main branch then I might as well delve into a fix for this.

Here's something that is compatible with Python 2:
```py
from time import mktime
mktime((2020, 10, 1, 0, 0, 0, -1, -1, -1))
```

Which is also compatible with Python 3, I'll update the code to implement this fix since the main branch still has Python 2 support built in to it while the other branches forego the Python 2 support altogether.

**Comment by Dracovian** [comment]
Let me know if the fix has worked for you, if so then I'll close this issue and probably get right on to refactoring this whole repository since it's been long overdue for an overhaul.

**Comment by Ajinson** [comment]
sorry im still novice, which line at discord.py that i need to change to:

from time import mktime
mktime((2020, 10, 1, 0, 0, 0, -1, -1, -1))

**Comment by Dracovian** [comment]
> sorry im still novice, which line at discord.py that i need to change to:

Oh no, I updated the code to fix that error when ran through Python 2, you just have to pull the changes to the repo (or simply grab the entire `discord.py` file from the current repository which should already include the fix for that particular error message.

**Comment by Ajinson** [comment]
i tried with the new code, got error:
```python
Traceback (most recent call last):
  File "discord.py", line 347, in <module>
    ds.grab_server_data()
  File "discord.py", line 323, in grab_server_data
    self.get_server_name(server),
  File "discord.py", line 163, in get_server_name
    request = SimpleRequest(self.headers).request
  File "/Users/tiyotriyanto/Downloads/Discord-Scraper-master/SimpleRequests/SimpleRequest.py", line 34, in __init__
    from .SimpleRequestsPy3 import SimpleRequests
  File "/Users/tiyotriyanto/Downloads/Discord-Scraper-master/SimpleRequests/SimpleRequestsPy3.py", line 34
    urlpath = f"/{'/'.join(urlsplices[3::])}"
                                            ^
SyntaxError: invalid syntax

**Comment by Dracovian** [comment]
The Python 2 version appears to be working (unfortunately it worked too well and so you ended up hitting the ratelimiter for Discord meaning we have to bump up the timeout between requests).

There should be no reason for the error on Python 3 unless you're running with a version older than Python 3.6 which is when f-strings were introduced. I should suggest that you update your Python 3 installation since Python 3.6 launched back in December 2016 and every version before Python 3.6 is no longer supported by the Python developers.

Could you please confirm the version of Python 3 you have installed by running this command: `python3 --version`

**Comment by Ajinson** [comment]
im running
```python
Python 3.5.0a3

**Comment by Dracovian** [comment]
An alpha build as well, right now I'm writing up the next major overhaul for this script and I'll be sure to make sure not to use f-strings anywhere in the code and I'll be paying more attention towards that nasty little ratelimiter that Discord has set up to hopefully lower the chances of seeing HTTP: 429 errors.

In the meantime you might want to consider upgrading your Python 3 to something more up-to-date since I can't speak on behalf of other scripts you might encounter that will be using language features that were added to Python after Python 3.5; but I will at least do what I can to make sure that this script will run on as many versions of Python as possible *(within reason)*.

There's currently no ETA on when the next commit is going to be made but I will keep this issue open until I push the new code and check with you to see if it works before closing this issue.

**Comment by Ajinson** [comment]
i didnt know im running python 3.5 , im update my python atm.

```python
Updating Homebrew...
Warning: python@3.9 3.9.0_1 is already installed, it's just not linked
You can use `brew link python@3.9` to link this version.

**Comment by Ajinson** [comment]
looking forward for your next update, thanks.

**Comment by Dracovian** [comment]
@Ajinson okay, I deleted the experimental_requests branch and updated the experimental branch with the new code, but unfortunately Discord's CDNs or their servers decided to crap out on me during the testing but I was able to download some of the files from the servers I targeted while it was up.

I do plan on merging the experimental branch into the main branch whenever I get everything up-and-running and working. You'll note that I've made some major modifications to how the token files are stored in response to a recent fork where the person who forked the code accidentally left his/her authorization token in the config and pushed that modified config file to their forked repo (which is publicly viewable by all).

So let me know if you have any better luck with the new code (know that it's incomplete since none of the options are there and it won't be grabbing all that it will grab whenever I merge it: https://github.com/Dracovian/Discord-Scraper/tree/experimental

**Comment by Ajinson** [comment]
@Dracovian i updated my python and now its **Python 3.7.3** and used the experimental code, created my.token.txt like such:
```python
{
  "token": "My_DIscord_TOKEN"
}
```
and then added server and channel ID to guilds bracket in config.json

```python
[WARN] Unable to gather guild name from its ID, generating one instead!
[WARN] HTTP 401 from https://discordapp.com/api/v8/channels/773952800367050782.
[WARN] Unable to gather channel name from its ID, generating one instead!
[WARN] HTTP 401 from https://discordapp.com/api/v8/channels/773952800367050782/messages/search?min_id=759625364275200000&max_id=759987747946496000&has=image&has=file&has=embed&has=link&has=video&include_nsfw=true.
[WARN] HTTP 401 from https://discordapp.com/api/v8/guilds/312476149190098944.
[WARN] Unable to gather guild name from its ID, generating one instead!
[WARN] HTTP 401 from https://discordapp.com/api/v8/channels/773952800367050782.

**Comment by Dracovian** [comment]
The token file isn't JSON, it's just a single line with the authorization token in it (nothing else), there's more information on the config file options for the experimental branch here: https://github.com/Dracovian/Discord-Scraper/wiki/Experimental-Branch-Information#tokenfile

**Comment by Ajinson** [comment]
ok got it working, i tried output the scrape but return nothing
```python
python3 discord.py -o TEST.csv --csv
```

**Comment by Dracovian** [comment]
There are no commandline arguments for the script, it's as simple as `python3 discord.py`

All of the configuring is done in the config.json file.

**Comment by Ajinson** [comment]
for a sec i thought it was working (Downloading...) but then got these error
also, the scrape folder only consist of .png files
```python
Downloading        ...{'type': 'link', 'url': 'http://markets.cboe.com/us/options/market_statistics/current/?mkt=cone', 'title': 'Current Market Statistics', 'color': 16777215}
{'type': 'link', 'url': 'https://www.investing.com/economic-calendar/', 'title': 'Economic Calendar - Investing.com', 'description': 'Economic calendar: get indicators in real-time as economic events are announced and see the immediate global market impact - Including previous, forecast and actual figures.', 'provider': {'name': 'Investing.com', 'url': None}, 'thumbnail': {'url': 'https://i-invdn-com.akamaized.net/redesign/images/seo/v2/investing_300X300.png', 'proxy_url': 'https://images-ext-2.discordapp.net/external/3nLzJctb93aMNDfScw8Wpoz_WTHbR5GtOGKqoN3kFRs/https/i-invdn-com.akamaized.net/redesign/images/seo/v2/investing_300X300.png', 'width': 300, 'height': 300}}
{'type': 'link', 'url': 'https://www.investing.com/indices/indices-futures', 'title': 'Stock Futures | Index & Market Futures - Investing.com', 'description': "Stock futures data with real-time & premarket rates from the Nasdaq, Dow Jones, S&P 500. This table displays stock market futures with live streaming rates for 31 of the world's top stock indexes.", 'provider': {'name': 'Investing.com', 'url': None}, 'thumbnail': {'url': 'https://i-invdn-com.akamaized.net/redesign/images/seo/v2/investing_300X300.png', 'proxy_url': 'https://images-ext-2.discordapp.net/external/3nLzJctb93aMNDfScw8Wpoz_WTHbR5GtOGKqoN3kFRs/https/i-invdn-com.akamaized.net/redesign/images/seo/v2/investing_300X300.png', 'width': 300, 'height': 300}}
{'type': 'link', 'url': 'https://www.tradingview.com/chart/Nw7E5etL/', 'title': 'Live stock, index, futures, Forex and Bitcoin charts on TradingView', 'description': 'Interactive financial charts for analysis and generating trading ideas on TradingView!', 'color': 2501438, 'provider': {'name': 'TradingView', 'url': None}, 'thumbnail': {'url': 'https://www.tradingview.com/static/images/logo-v-1200x630.png', 'proxy_url': 'https://images-ext-2.discordapp.net/external/XspLEsyZKV3VCriFPKWk7JoLpHnOxVwZZYhtJd-UlOo/https/www.tradingview.com/static/images/logo-v-1200x630.png', 'width': 1200, 'height': 630}}
{'type': 'link', 'url': 'https://www.tradingview.com/chart/uZ99WEZA/', 'title': 'Live stock, index, futures, Forex and Bitcoin charts on TradingView', 'description': 'Interactive financial charts for analysis and generating trading ideas on TradingView!', 'color': 2501438, 'provider': {'name': 'TradingView', 'url': None}, 'thumbnail': {'url': 'https://www.tradingview.com/static/images/logo-v-1200x630.png', 'proxy_url': 'https://images-ext-2.discordapp.net/external/XspLEsyZKV3VCriFPKWk7JoLpHnOxVwZZYhtJd-UlOo/https/www.tradingview.com/static/images/logo-v-1200x630.png', 'width': 1200, 'height': 630}}
{'type': 'link', 'url': 'https://www.tradingview.com/chart/oruJS5z1/', 'title': 'Live stock, index, futures, Forex and Bitcoin charts on TradingView', 'description': 'Interactive financial charts for analysis and generating trading ideas on TradingView!', 'color': 2501438, 'provider': {'name': 'TradingView', 'url': None}, 'thumbnail': {'url': 'https://www.tradingview.com/static/images/logo-v-1200x630.png', 'proxy_url': 'https://images-ext-2.discordapp.net/external/XspLEsyZKV3VCriFPKWk7JoLpHnOxVwZZYhtJd-UlOo/https/www.tradingview.com/static/images/logo-v-1200x630.png', 'width': 1200, 'height': 630}}
Traceback (most recent call last):
  File "discord.py", line 102, in <module>
    startGuild(discordscraper, guild, channel)
  File "discord.py", line 85, in startGuild
    startGuild(scraper, guild, channel, day)
  File "discord.py", line 85, in startGuild
    startGuild(scraper, guild, channel, day)
  File "discord.py", line 85, in startGuild
    startGuild(scraper, guild, channel, day)
  [Previous line repeated 139 more times]
  File "discord.py", line 79, in startGuild
    scraper.checkMimetypes(data)
  File "/Users/tiyotriyanto/Downloads/Discord-Scraper-experimental/module/DiscordScraper.py", line 399, in checkMimetypes
    proxied = embed['video']['proxy_url']
KeyError: 'proxy_url'

**Comment by Dracovian** [comment]
Ah yes, I should probably push the updated code... done. This should fix the current issue but it might introduce another one as I saw during the testing where the script crashes (and in one case crashed so spectacularly that I ended up with a core dump).
