### ISSUE TITLE
incomplete files cause a crash

### ISSUE THREAD

**Issue by Matthew-Bradley** [Dracovian/Discord-Scraper#61]
running the script, it appears to crash if discord terminates a download prematurely.

below is the trace I was able to catch when the crash occurred:

Unknown exception: HTTP 429 Too Many Requests                                                                                                         
Unknown exception: HTTP 429 Too Many Requests                                                                                                         
Unknown exception: HTTP 429 Too Many Requests                                                                                                         
Unknown exception: HTTP 429 Too Many Requests                                                                                                         
Unknown exception: HTTP 429 Too Many Requests                                                                                                         
Unknown exception: HTTP 429 Too Many Requests                                                                                                         
Unknown exception: HTTP 415 Unsupported Media Type                                                                                                    
Unknown exception: HTTP 524 Origin Time-out                                                                                                           
Unknown exception: HTTP 521 Origin Down                                                                                                               
Traceback (most recent call last):                                                                                                                    
  File "discord.py", line 347, in <module>                                                                                                            
    ds.grab_server_data()                                                                                                                             
  File "discord.py", line 327, in grab_server_data                                                                                                    
    self.grab_data(folder, server, channel)                                                                                                           
  File "discord.py", line 307, in grab_data                                                                                                           
    self.check_config_mimetypes(message, folder)                                                                                                      
  File "discord.py", line 231, in check_config_mimetypes                                                                                              
    self.download(attachment['proxy_url'], folder)                                                                                                    
  File "discord.py", line 219, in download                                                                                                            
    request.stream_file(url, folder, filename, self.buffer)                                                                                           
  File "/initial-pool/scratch/temp/discord_scrape/Discord-Scraper/SimpleRequests/SimpleRequestsPy3.py", line 149, in stream_file                      
    filestream.write(resp.read())                                          
  File "/usr/lib/python3.8/http/client.py", line 471, in read                                                                                         
    s = self._safe_read(self.length)                                       
  File "/usr/lib/python3.8/http/client.py", line 614, in _safe_read                                                                                   
    raise IncompleteRead(data, amt-len(data))                                                                                                         
http.client.IncompleteRead: IncompleteRead(10508941 bytes read, 576532 more expected)

**Comment by Matthew-Bradley** [comment]
another trace:

Unknown exception: HTTP 429 Too Many Requests
Unknown exception: HTTP 429 Too Many Requests
Unknown exception: HTTP 429 Too Many Requests
Unknown exception: HTTP 415 Unsupported Media Type                                                                                                    
Unknown exception: HTTP 415 Unsupported Media Type                                                                                                    
Traceback (most recent call last):                              
  File "discord.py", line 347, in <module>
    ds.grab_server_data()
  File "discord.py", line 327, in grab_server_data
    self.grab_data(folder, server, channel)
  File "discord.py", line 307, in grab_data
    self.check_config_mimetypes(message, folder)
  File "discord.py", line 231, in check_config_mimetypes
    self.download(attachment['proxy_url'], folder)
  File "discord.py", line 219, in download
    request.stream_file(url, folder, filename, self.buffer)
  File "/initial-pool/scratch/temp/discord_scrape/Discord-Scraper/SimpleRequests/SimpleRequestsPy3.py", line 149, in stream_file
    filestream.write(resp.read())
  File "/usr/lib/python3.8/http/client.py", line 471, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.8/http/client.py", line 614, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(986894 bytes read, 351643 more expected)

**Comment by Matthew-Bradley** [comment]
ditto.

Unknown exception: HTTP 429 Too Many Requests
Unknown exception: HTTP 429 Too Many Requests
Unknown exception: HTTP 429 Too Many Requests
Traceback (most recent call last):
  File "discord.py", line 347, in <module>
    ds.grab_server_data()
  File "discord.py", line 327, in grab_server_data
    self.grab_data(folder, server, channel)
  File "discord.py", line 307, in grab_data
    self.check_config_mimetypes(message, folder)
  File "discord.py", line 231, in check_config_mimetypes
    self.download(attachment['proxy_url'], folder)
  File "discord.py", line 219, in download
    request.stream_file(url, folder, filename, self.buffer)
  File "/initial-pool/scratch/temp/discord_scrape/Discord-Scraper/SimpleRequests/SimpleRequestsPy3.py", line 149, in stream_file
    filestream.write(resp.read())
  File "/usr/lib/python3.8/http/client.py", line 471, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.8/http/client.py", line 614, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(2319246 bytes read, 2009677 more expected)

**Comment by Matthew-Bradley** [comment]
It seems like one possible fix would be to catch the incomplete read and retry the download, though I don't know the underlying cause so I don't know if it would immediately work again (if this is an intermittent issue or a higher level one like a session timeout)

**Comment by Dracovian** [comment]
Was this occurring on the main branch or the experimental branch code?
