### ISSUE TITLE
configuration error

### ISSUE THREAD

**Issue by SimpleChris0** [Dracovian/Discord-Scraper#66]
I keep getting this token error, i dont know whate fuck im doing wrong.

[ERROR]: Authorization token file can not be found at the following location: C:\Program Files (x86)\pycharm projects\Discord scrapper\Discord-Scraper-experimental\{mytoken.token}
Traceback (most recent call last):
  File "C:\Program Files (x86)\pycharm projects\Discord scrapper\Discord-Scraper-experimental\discord.py", line 195, in <module>
    discordscraper = DiscordScraper()
  File "C:\Program Files (x86)\pycharm projects\Discord scrapper\Discord-Scraper-experimental\module\DiscordScraper.py", line 152, in __init__
    error('Authorization token file can not be found at the following location: {0}'.format(tokenfile))
  File "C:\Program Files (x86)\pycharm projects\Discord scrapper\Discord-Scraper-experimental\module\DiscordScraper.py", line 87, in error
    exit()
TypeError: _exit() missing required argument 'status' (pos 1)

Hope someone can help me

**Comment by Dracovian** [comment]
So there's two problems there:

1. You put down the token file name in the config.json file as `"{mytoken.token}"` instead of `"mytoken.token"` or the script somehow placed that in the curly format brackets and forgot to add the trailing path separator between the token and the `Discord-Scraper-experimental` folder name.

2. I forgot to put a `1` in the exit function call on line 87 which I'm about to rectify as soon as I send this response.

**Comment by Dracovian** [comment]
Wait what?

I didn't want to close the issue.

**Comment by SimpleChris0** [comment]
Ok thank you, i got it working now but it still shows me HTTP 249 warnings

**Comment by Dracovian** [comment]
Yes, HTTP 429 is the ratelimiter and I figured that the sleep time was adequate enough to prevent hitting the ratelimiter but I might have to start looking into what Discord is doing regarding these recent API updates in regards to rate limiting.

**Comment by worldpe** [comment]
> 1. You put down the token file name in the config.json file as `"{mytoken.token}"` instead of `"mytoken.token"` or the script 
In the example config, that is how it is formatted, you have a more understandable example config in the wiki than in the repo
