### ISSUE TITLE
AttributeError: 'DiscordConfig' object has no attribute 'tokenfile'

### ISSUE THREAD

**Issue by h1lyl1ly** [Dracovian/Discord-Scraper#76]
Traceback (most recent call last):
  File "C:\Users\leadm\Desktop\Discord-Scraper-experimental\discord.py", line 195, in <module>
    discordscraper = DiscordScraper()
  File "C:\Users\leadm\Desktop\Discord-Scraper-experimental\module\DiscordScraper.py", line 148, in __init__
    tokenfile = path.join(getcwd(), config.tokenfile)
AttributeError: 'DiscordConfig' object has no attribute 'tokenfile'

**Comment by h1lyl1ly** [comment]
[WARN] HTTP 429 from?
{"message": "401: Unauthorized", "code": 0}
